<?php

/**
 * Edit general settings of Coworking Space Manager
 */
function show_settings() {
    if (!current_user_can('manage_options')) {
        csm_error('You do not have sufficient permissions to access this page', true);
    }

    $CsmSettings = new CsmSettings();
    $data = $CsmSettings->all();


    include(CSM_PLUGIN_PATH . '/app/assets/currency-symbols.php');

    //Edit the settings
    if (isset($_POST['action']) && $_POST['action'] === 'change-settings') {
        $data = $_POST;
        foreach ($data as $k => $v) {
            $data[$k] = stripslashes($v);
        }

        //Upload a logo for the coworking space
        if ($_FILES['csm_logo']['size'] > 0) {
            if (!function_exists('wp_handle_upload')) {
                require_once( ABSPATH . 'wp-admin/includes/file.php' );
            }
            $uploadedfile = $_FILES['csm_logo'];
            $upload_overrides = array('test_form' => false);
            $movefile = wp_handle_upload($uploadedfile, $upload_overrides);
            
            if ($movefile && !isset($movefile['error'])) {
                $data['csm_logo'] = $movefile['url'];
            } else {
                /**
                 * Error generated by _wp_handle_upload()
                 * @see _wp_handle_upload() in wp-admin/includes/file.php
                 */
                throw new Exception($movefile['error']);
            }
        }

        try {
            $CsmSettings->update($data);
            csm_update('Settings updated');
            $data['csm_logo'] = stripslashes(get_option('csm-logo'));
        } catch (\Exception $e) {
            csm_error($e->getMessage());
        }
    }

    include(CSM_PLUGIN_PATH . 'app/views/settings.view.php');
}

?>